# This injects some extra testing stuff into our image

FROM scratch as context
# We only need this stuff in the initial context
COPY hack /hack
COPY contrib /contrib

FROM localhost/bootc
# We support e.g. adding cloud-init
ARG variant=
# And this layer has additional stuff for testing, such as nushell etc.
RUN --mount=type=bind,from=context,target=/run/context <<EORUN
set -xeuo pipefail
/run/context/hack/provision-derived.sh "$variant"
# Add some testing kargs into our dev builds
install -D -t /usr/lib/bootc/kargs.d /run/context/hack/test-kargs/*
# Also copy in some default install configs we use for testing
install -D -t /usr/lib/bootc/install/ /run/context/hack/install-test-configs/*
# Finally, test our own linting
bootc container lint --fatal-warnings
EORUN
