name: 'Update Generated Files'

# This workflow is triggered on a schedule (every day at 3:15 AM UTC)
# and can also be triggered manually from the GitHub Actions UI.
on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * *'

jobs:
  update-and-pr:
    name: 'Update Generated Files and Create PR'
    runs-on: ubuntu-latest
    container: quay.io/coreos-assembler/fcos-buildroot:testing-devel
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Mark git directory as safe'
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        shell: bash

      - name: 'Install dependencies'
        run: ./ci/installdeps.sh
        shell: bash

      - name: 'Install pandoc'
        run: dnf -y install pandoc
        shell: bash

      - name: 'Update generated docs'
        run: cargo xtask update-generated
        shell: bash

      - name: 'Create Pull Request'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update generated files'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          signoff: true
          title: 'docs: Update generated'
          body: |
            This PR was auto-generated by a GitHub Actions workflow.

            It contains updates to doc files generated by `cargo xtask update-generated`.
          branch: 'actions/update-generated-files'
          labels: 'documentation'

